"""Full complex-symmetric-width multidimensional Gaussian TDVP for v0.27.0.

The normalized nuclear packets are

    g_I(R) = [det(Gamma_I)/pi**D]**(1/4)
             exp[-x_I.T (Gamma_I-i B_I) x_I/2 + i p_I.T x_I],

where ``x_I = R-q_I``, ``Gamma_I = exp(E_I)`` is real symmetric positive
definite, and ``B_I`` is real symmetric.  The log-Euclidean coordinate ``E``
guarantees positivity throughout nonlinear iteration and obeys

    E -> O E O.T,  B -> O B O.T

under every orthogonal coordinate transformation.  Symmetric matrices are
packed with an orthonormal ``svec`` convention: diagonal entries are unchanged
and off-diagonal entries are multiplied by ``sqrt(2)``.  Consequently the
matrix-coordinate transformation is itself orthogonal in parameter space.

All matrix elements and McLachlan tangent projections are analytic for the
fixed-frame quadratic Hamiltonian contract.  Correlated complex-normal moments
through total degree four are generated by a multivariate Wick recurrence.
"""

from dataclasses import asdict, dataclass
import hashlib
import itertools
import json

import numpy as np
from scipy.optimize import root

from .multigaussian_tdvp_v251 import MetricSolveReceiptV251, solve_variational_metric_v251
from .multidimensional_gaussian_tdvp_v260 import DiagonalGaussianSpinorStateV260
from .multidimensional_soc_v260 import QuadraticSpinHamiltonianNDV260


CORRELATED_TDVP_SCHEMA_V270 = "gnd-correlated-width-multidimensional-tdvp-v0.27.0"
CORRELATED_TDVP_ANSATZ_V270 = (
    "coupled normalized multidimensional Gaussians with full log-Euclidean SPD width "
    "matrices, full symmetric chirp matrices, and complete fixed-frame spinors"
)
VARIATIONAL_PRINCIPLE_V270 = "real-parameter McLachlan time-dependent variation"
VARIATIONAL_INTEGRATOR_V270 = "fully implicit midpoint on the full-SVD TDVP vector field"
VARIATIONAL_METRIC_SOLVER_V270 = "full SVD with compatible-null-space audit"
WIDTH_CONVENTION_V270 = (
    "Gamma=exp(E) with real symmetric E; real symmetric B; orthonormal svec coordinates"
)


def _canonical_v270(value):
    if isinstance(value, np.generic):
        return _canonical_v270(value.item())
    if isinstance(value, complex):
        return [float(value.real), float(value.imag)]
    if isinstance(value, np.ndarray):
        return _canonical_v270(value.tolist())
    if isinstance(value, dict):
        return {
            str(key): _canonical_v270(item)
            for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
        }
    if isinstance(value, (tuple, list)):
        return [_canonical_v270(item) for item in value]
    if isinstance(value, float):
        if not np.isfinite(value):
            raise ValueError("v0.27.0 canonical data cannot contain non-finite values.")
        return float(value)
    if value is None or isinstance(value, (str, int, bool)):
        return value
    raise TypeError(f"unsupported v0.27.0 canonical value: {type(value).__name__}")


def _sha256_v270(value):
    payload = json.dumps(
        _canonical_v270(value), sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _complex_pairs_v270(value):
    array = np.asarray(value, dtype=complex)
    return np.stack((array.real, array.imag), axis=-1).tolist()


def _scaled_norm_v270(left, right):
    left = np.asarray(left)
    right = np.asarray(right)
    if left.shape != right.shape:
        return float("inf")
    scale = max(float(np.linalg.norm(left)), float(np.linalg.norm(right)), 1.0)
    return float(np.linalg.norm(left - right) / scale)


def symmetric_pairs_v270(ndim):
    ndim = int(ndim)
    if ndim < 1:
        raise ValueError("symmetric-matrix dimension must be positive.")
    return tuple((a, b) for a in range(ndim) for b in range(a, ndim))


def symmetric_size_v270(ndim):
    ndim = int(ndim)
    return ndim * (ndim + 1) // 2


def svec_v270(matrix):
    """Pack a real symmetric matrix in a Frobenius-orthonormal basis."""

    matrix = np.asarray(matrix, dtype=float)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError("svec requires a square matrix.")
    if not np.all(np.isfinite(matrix)) or _scaled_norm_v270(matrix, matrix.T) > 2.0e-12:
        raise ValueError("svec requires a finite symmetric matrix.")
    values = []
    for a, b in symmetric_pairs_v270(matrix.shape[0]):
        values.append(matrix[a, b] if a == b else np.sqrt(2.0) * matrix[a, b])
    return np.asarray(values, dtype=float)


def smat_v270(vector, ndim):
    """Invert :func:`svec_v270`."""

    vector = np.asarray(vector, dtype=float)
    ndim = int(ndim)
    if vector.shape != (symmetric_size_v270(ndim),) or not np.all(np.isfinite(vector)):
        raise ValueError("symmetric vector has an invalid shape or values.")
    matrix = np.zeros((ndim, ndim), dtype=float)
    for value, (a, b) in zip(vector, symmetric_pairs_v270(ndim)):
        matrix[a, b] = matrix[b, a] = value if a == b else value / np.sqrt(2.0)
    return matrix


def symmetric_basis_v270(ndim):
    """Return matrices F_k satisfying Tr(F_k.T F_l)=delta_kl."""

    basis = []
    for index in range(symmetric_size_v270(ndim)):
        vector = np.zeros(symmetric_size_v270(ndim), dtype=float)
        vector[index] = 1.0
        basis.append(smat_v270(vector, ndim))
    return tuple(basis)


def _symmetric_eigendecomposition_v270(matrix, name):
    matrix = np.asarray(matrix, dtype=float)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError(f"{name} must be square.")
    if not np.all(np.isfinite(matrix)) or _scaled_norm_v270(matrix, matrix.T) > 2.0e-11:
        raise ValueError(f"{name} must be finite and symmetric.")
    values, vectors = np.linalg.eigh(0.5 * (matrix + matrix.T))
    return values, vectors


def log_spd_v270(width_matrix):
    values, vectors = _symmetric_eigendecomposition_v270(width_matrix, "width matrix")
    if float(np.min(values)) <= 0.0:
        raise ValueError("width matrix must be positive definite.")
    return (vectors * np.log(values)) @ vectors.T


def exp_symmetric_v270(log_width_matrix):
    values, vectors = _symmetric_eigendecomposition_v270(log_width_matrix, "log-width matrix")
    if float(np.max(np.abs(values))) > 700.0:
        raise ValueError("log-width eigenvalue is outside floating-point range.")
    return (vectors * np.exp(values)) @ vectors.T


def exp_frechet_symmetric_v270(log_width_matrix, direction):
    """Exact Frechet derivative D exp(E)[F] for real symmetric E and F."""

    values, vectors = _symmetric_eigendecomposition_v270(log_width_matrix, "log-width matrix")
    direction = np.asarray(direction, dtype=float)
    if direction.shape != log_width_matrix.shape or _scaled_norm_v270(direction, direction.T) > 2.0e-11:
        raise ValueError("log-width direction must be a compatible symmetric matrix.")
    transformed = vectors.T @ direction @ vectors
    exp_values = np.exp(values)
    divided = np.empty((len(values), len(values)), dtype=float)
    for i in range(len(values)):
        for j in range(len(values)):
            delta = values[i] - values[j]
            if abs(delta) < 1.0e-10:
                divided[i, j] = np.exp(0.5 * (values[i] + values[j])) * (
                    1.0 + delta**2 / 24.0
                )
            else:
                divided[i, j] = exp_values[j] * np.expm1(delta) / delta
    result = vectors @ (divided * transformed) @ vectors.T
    return 0.5 * (result + result.T)


def rotate_symmetric_v270(matrix, orthogonal):
    matrix = np.asarray(matrix, dtype=float)
    orthogonal = np.asarray(orthogonal, dtype=float)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError("matrix to rotate must be square.")
    if orthogonal.shape != matrix.shape or _scaled_norm_v270(
        orthogonal @ orthogonal.T, np.eye(matrix.shape[0])
    ) > 2.0e-11:
        raise ValueError("coordinate transformation must be orthogonal.")
    return orthogonal @ matrix @ orthogonal.T


def _zero_index_v270(ndim):
    return (0,) * int(ndim)


def _monomial_v270(ndim, axes=()):
    powers = [0] * int(ndim)
    for axis in axes:
        powers[int(axis)] += 1
    return tuple(powers)


def _poly_add_v270(*polynomials):
    result = {}
    for polynomial in polynomials:
        for powers, value in polynomial.items():
            result[powers] = result.get(powers, 0.0 + 0.0j) + complex(value)
    return {powers: value for powers, value in result.items() if abs(value) > 0.0}


def _poly_scale_v270(polynomial, scale):
    return {powers: complex(scale) * value for powers, value in polynomial.items()}


def _poly_multiply_v270(left, right):
    result = {}
    for powers_left, value_left in left.items():
        for powers_right, value_right in right.items():
            powers = tuple(a + b for a, b in zip(powers_left, powers_right))
            result[powers] = result.get(powers, 0.0 + 0.0j) + value_left * value_right
    return {powers: value for powers, value in result.items() if abs(value) > 0.0}


def _poly_conjugate_v270(polynomial):
    return {powers: np.conj(value) for powers, value in polynomial.items()}


def _linear_polynomial_v270(ndim, constant, slopes):
    slopes = np.asarray(slopes, dtype=complex)
    if slopes.shape != (ndim,):
        raise ValueError("linear polynomial slopes have an invalid shape.")
    result = {_zero_index_v270(ndim): complex(constant)}
    for axis, value in enumerate(slopes):
        if value != 0.0:
            result[_monomial_v270(ndim, (axis,))] = complex(value)
    return result


def _shifted_quadratic_v270(matrix, center):
    """Polynomial for ``(R-center).T matrix (R-center)``."""

    matrix = np.asarray(matrix, dtype=complex)
    center = np.asarray(center, dtype=float)
    ndim = len(center)
    if matrix.shape != (ndim, ndim) or _scaled_norm_v270(matrix, matrix.T) > 2.0e-11:
        raise ValueError("quadratic-form matrix must be compatible and symmetric.")
    result = {_zero_index_v270(ndim): complex(center @ matrix @ center)}
    linear = -2.0 * (matrix @ center)
    for axis, value in enumerate(linear):
        if value != 0.0:
            result[_monomial_v270(ndim, (axis,))] = complex(value)
    for a in range(ndim):
        for b in range(ndim):
            powers = _monomial_v270(ndim, (a, b))
            result[powers] = result.get(powers, 0.0 + 0.0j) + matrix[a, b]
    return {powers: value for powers, value in result.items() if abs(value) > 0.0}


def _complex_logdet_positive_stable_v270(matrix):
    """Log determinant without wrapping the summed eigenvalue phases."""

    eigenvalues = np.linalg.eigvals(np.asarray(matrix, dtype=complex))
    if not np.all(np.isfinite(eigenvalues)) or np.min(eigenvalues.real) <= 0.0:
        raise ValueError("complex Gaussian precision lacks a positive-stable spectrum.")
    return complex(np.sum(np.log(eigenvalues)))


def cross_correlated_gaussian_data_v270(
    qi, pi, width_i, chirp_i, qj, pj, width_j, chirp_j
):
    """Return exact overlap, mean, and full covariance for two packets."""

    qi = np.asarray(qi, dtype=float)
    pi = np.asarray(pi, dtype=float)
    qj = np.asarray(qj, dtype=float)
    pj = np.asarray(pj, dtype=float)
    width_i = np.asarray(width_i, dtype=float)
    chirp_i = np.asarray(chirp_i, dtype=float)
    width_j = np.asarray(width_j, dtype=float)
    chirp_j = np.asarray(chirp_j, dtype=float)
    ndim = len(qi) if qi.ndim == 1 else 0
    if ndim < 1 or any(value.shape != (ndim,) for value in (pi, qj, pj)):
        raise ValueError("cross-Gaussian centres and momenta must be equally sized vectors.")
    if any(value.shape != (ndim, ndim) for value in (width_i, chirp_i, width_j, chirp_j)):
        raise ValueError("cross-Gaussian width and chirp matrices have invalid shapes.")
    if not all(
        np.all(np.isfinite(value))
        for value in (qi, pi, width_i, chirp_i, qj, pj, width_j, chirp_j)
    ):
        raise ValueError("cross-Gaussian data must be finite.")
    wi, _ = _symmetric_eigendecomposition_v270(width_i, "bra width matrix")
    wj, _ = _symmetric_eigendecomposition_v270(width_j, "ket width matrix")
    if min(float(np.min(wi)), float(np.min(wj))) <= 0.0:
        raise ValueError("cross-Gaussian widths must be positive definite.")
    if _scaled_norm_v270(chirp_i, chirp_i.T) > 2.0e-11 or _scaled_norm_v270(
        chirp_j, chirp_j.T
    ) > 2.0e-11:
        raise ValueError("cross-Gaussian chirps must be symmetric.")
    bra_precision = width_i + 1.0j * chirp_i
    ket_precision = width_j - 1.0j * chirp_j
    combined = bra_precision + ket_precision
    linear = bra_precision @ qi + ket_precision @ qj + 1.0j * (pj - pi)
    constant = (
        -0.5 * qi @ bra_precision @ qi
        - 0.5 * qj @ ket_precision @ qj
        + 1.0j * pi @ qi
        - 1.0j * pj @ qj
    )
    covariance = np.linalg.inv(combined)
    mean = covariance @ linear
    logdet_i = float(np.sum(np.log(wi)))
    logdet_j = float(np.sum(np.log(wj)))
    logdet_combined = _complex_logdet_positive_stable_v270(combined)
    log_overlap = (
        0.25 * (logdet_i + logdet_j)
        + 0.5 * ndim * np.log(2.0)
        - 0.5 * logdet_combined
        + constant
        + 0.5 * linear @ covariance @ linear
    )
    overlap = complex(np.exp(log_overlap))
    if not np.isfinite(overlap) or not np.all(np.isfinite(mean)) or not np.all(np.isfinite(covariance)):
        raise ValueError("correlated cross-Gaussian moments are non-finite.")
    return overlap, mean, covariance


def correlated_moment_table_v270(overlap, mean, covariance, maximum_degree=4):
    """Generate all raw multivariate moments up to ``maximum_degree``."""

    mean = np.asarray(mean, dtype=complex)
    covariance = np.asarray(covariance, dtype=complex)
    ndim = len(mean) if mean.ndim == 1 else 0
    if ndim < 1 or covariance.shape != (ndim, ndim):
        raise ValueError("complex-normal moment parameters have invalid shapes.")
    if not isinstance(maximum_degree, (int, np.integer)) or isinstance(
        maximum_degree, (bool, np.bool_)
    ) or int(maximum_degree) < 0:
        raise ValueError("maximum moment degree must be a nonnegative integer.")
    cache = {_zero_index_v270(ndim): 1.0 + 0.0j}

    def moment(powers):
        powers = tuple(int(value) for value in powers)
        if powers in cache:
            return cache[powers]
        axis = next(index for index, value in enumerate(powers) if value > 0)
        reduced = list(powers)
        reduced[axis] -= 1
        reduced = tuple(reduced)
        value = mean[axis] * moment(reduced)
        for other, multiplicity in enumerate(reduced):
            if multiplicity:
                twice_reduced = list(reduced)
                twice_reduced[other] -= 1
                value += multiplicity * covariance[axis, other] * moment(tuple(twice_reduced))
        cache[powers] = complex(value)
        return cache[powers]

    for powers in itertools.product(range(int(maximum_degree) + 1), repeat=ndim):
        if sum(powers) <= int(maximum_degree):
            moment(powers)
    return complex(overlap), cache


def integrate_correlated_polynomial_v270(polynomial, moment_table):
    overlap, moments = moment_table
    value = 0.0 + 0.0j
    for powers, coefficient in polynomial.items():
        if powers not in moments:
            raise ValueError("polynomial degree exceeds the correlated moment table.")
        value += coefficient * overlap * moments[powers]
    return complex(value)


@dataclass(frozen=True)
class CorrelatedVariationalSettingsV270:
    metric_relative_cutoff: float = 1.0e-10
    metric_absolute_cutoff: float = 1.0e-12
    maximum_retained_condition_number: float = 1.0e10
    null_rhs_relative_tolerance: float = 3.0e-9
    linear_residual_relative_tolerance: float = 3.0e-9
    nonlinear_residual_tolerance: float = 8.0e-10
    nonlinear_xtol: float = 1.0e-10
    nonlinear_max_function_evaluations: int = 1600
    structural_tolerance: float = 5.0e-10
    maximum_step_norm_drift: float = 1.0e-7
    minimum_width_eigenvalue: float = 1.0e-8
    maximum_width_eigenvalue: float = 1.0e8
    maximum_chirp_spectral_radius: float = 1.0e8
    maximum_step_log_width_frobenius_change: float = 0.75
    allow_compatible_rank_deficiency: bool = True
    multidimensional_nuclear_motion: bool = True
    adaptive_full_widths: bool = True
    full_correlated_width_matrices: bool = True
    arbitrary_orthogonal_coordinate_covariance: bool = True
    fixed_electronic_frame: bool = True
    real_molecular_soc_provider: bool = False
    variational_principle: str = VARIATIONAL_PRINCIPLE_V270
    integrator: str = VARIATIONAL_INTEGRATOR_V270
    metric_solver: str = VARIATIONAL_METRIC_SOLVER_V270
    width_coordinates: str = WIDTH_CONVENTION_V270
    nonlinear_solver: str = "scipy.optimize.root-hybr"

    def validate(self):
        positive = (
            "metric_relative_cutoff", "metric_absolute_cutoff",
            "maximum_retained_condition_number", "null_rhs_relative_tolerance",
            "linear_residual_relative_tolerance", "nonlinear_residual_tolerance",
            "nonlinear_xtol", "structural_tolerance", "maximum_step_norm_drift",
            "minimum_width_eigenvalue", "maximum_width_eigenvalue",
            "maximum_chirp_spectral_radius", "maximum_step_log_width_frobenius_change",
        )
        for name in positive:
            value = float(getattr(self, name))
            if not np.isfinite(value) or value <= 0.0:
                raise ValueError(f"{name} must be finite and positive.")
        if self.metric_relative_cutoff >= 1.0:
            raise ValueError("metric_relative_cutoff must be below one.")
        if self.maximum_retained_condition_number < 1.0:
            raise ValueError("maximum retained condition number must be at least one.")
        if self.maximum_width_eigenvalue <= self.minimum_width_eigenvalue:
            raise ValueError("maximum width eigenvalue must exceed the minimum.")
        if isinstance(self.nonlinear_max_function_evaluations, (bool, np.bool_)) or not isinstance(
            self.nonlinear_max_function_evaluations, (int, np.integer)
        ) or int(self.nonlinear_max_function_evaluations) < 1:
            raise ValueError("nonlinear_max_function_evaluations must be a positive integer.")
        booleans = (
            "allow_compatible_rank_deficiency", "multidimensional_nuclear_motion",
            "adaptive_full_widths", "full_correlated_width_matrices",
            "arbitrary_orthogonal_coordinate_covariance", "fixed_electronic_frame",
            "real_molecular_soc_provider",
        )
        for name in booleans:
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be a native Boolean.")
        if not all(
            getattr(self, name)
            for name in (
                "allow_compatible_rank_deficiency", "multidimensional_nuclear_motion",
                "adaptive_full_widths", "full_correlated_width_matrices",
                "arbitrary_orthogonal_coordinate_covariance", "fixed_electronic_frame",
            )
        ):
            raise ValueError("v0.27.0 freezes the full-width variational contract as enabled.")
        if self.real_molecular_soc_provider:
            raise ValueError("v0.27.0 does not admit live molecular-SOC trajectories.")
        if self.variational_principle != VARIATIONAL_PRINCIPLE_V270:
            raise ValueError("the v0.27.0 variational principle is frozen.")
        if self.integrator != VARIATIONAL_INTEGRATOR_V270:
            raise ValueError("the v0.27.0 integrator is frozen.")
        if self.metric_solver != VARIATIONAL_METRIC_SOLVER_V270:
            raise ValueError("the v0.27.0 metric solver is frozen.")
        if self.width_coordinates != WIDTH_CONVENTION_V270:
            raise ValueError("the v0.27.0 width convention is frozen.")
        if self.nonlinear_solver != "scipy.optimize.root-hybr":
            raise ValueError("the v0.27.0 nonlinear solver is frozen.")
        return self

    def as_dict(self):
        self.validate()
        return _canonical_v270(asdict(self))


@dataclass(frozen=True)
class CorrelatedGaussianSpinorStateV270:
    q: np.ndarray
    p: np.ndarray
    width_matrices: np.ndarray
    chirp_matrices: np.ndarray
    coefficients: np.ndarray
    time_au: float = 0.0

    def __post_init__(self):
        for name in ("q", "p", "width_matrices", "chirp_matrices"):
            object.__setattr__(self, name, np.asarray(getattr(self, name), dtype=float).copy())
        object.__setattr__(self, "coefficients", np.asarray(self.coefficients, dtype=complex).copy())

    @property
    def ngaussian(self):
        return int(self.q.shape[0]) if self.q.ndim == 2 else 0

    @property
    def ndim(self):
        return int(self.q.shape[1]) if self.q.ndim == 2 else 0

    @property
    def nstate(self):
        return int(self.coefficients.shape[1]) if self.coefficients.ndim == 2 else 0

    @property
    def symmetric_size(self):
        return symmetric_size_v270(self.ndim)

    @property
    def parameter_count(self):
        return (
            2 * self.ngaussian * self.nstate
            + 2 * self.ngaussian * self.ndim
            + 2 * self.ngaussian * self.symmetric_size
        )

    @property
    def log_width_matrices(self):
        if self.width_matrices.shape != (self.ngaussian, self.ndim, self.ndim):
            raise ValueError("cannot form log widths from invalid packet matrices.")
        return np.asarray([log_spd_v270(matrix) for matrix in self.width_matrices])

    @property
    def width_eigenvalues(self):
        return np.linalg.eigvalsh(self.width_matrices)

    def validate(self, *, require_normalized=False, tolerance=5.0e-10):
        tolerance = float(tolerance)
        if not np.isfinite(tolerance) or tolerance <= 0.0:
            raise ValueError("state tolerance must be finite and positive.")
        if self.q.ndim != 2 or self.ngaussian < 1 or self.ndim < 1:
            raise ValueError("q must have shape (ngaussian,ndim) with positive dimensions.")
        if self.p.shape != self.q.shape:
            raise ValueError("q and p must have identical shapes.")
        expected_matrix_shape = (self.ngaussian, self.ndim, self.ndim)
        if self.width_matrices.shape != expected_matrix_shape or self.chirp_matrices.shape != expected_matrix_shape:
            raise ValueError("width and chirp arrays must have shape (ngaussian,ndim,ndim).")
        if self.coefficients.ndim != 2 or self.coefficients.shape[0] != self.ngaussian or self.nstate < 1:
            raise ValueError("coefficients must have shape (ngaussian,nstate).")
        if not all(
            np.all(np.isfinite(value))
            for value in (self.q, self.p, self.width_matrices, self.chirp_matrices, self.coefficients)
        ):
            raise ValueError("correlated Gaussian state contains non-finite values.")
        for width, chirp in zip(self.width_matrices, self.chirp_matrices):
            eigenvalues, _ = _symmetric_eigendecomposition_v270(width, "width matrix")
            if float(np.min(eigenvalues)) <= 0.0:
                raise ValueError("every width matrix must be positive definite.")
            _symmetric_eigendecomposition_v270(chirp, "chirp matrix")
        if not np.isfinite(float(self.time_au)):
            raise ValueError("state time must be finite.")
        norm = self.generalized_norm
        if not np.isfinite(norm) or norm <= 0.0:
            raise ValueError("correlated Gaussian state must have positive norm.")
        if require_normalized and abs(norm - 1.0) > tolerance:
            raise ValueError("correlated Gaussian state is not normalized.")
        return self

    def nuclear_overlap_matrix(self):
        if self.q.ndim != 2:
            raise ValueError("cannot build overlap from invalid packet arrays.")
        overlap = np.zeros((self.ngaussian, self.ngaussian), dtype=complex)
        for i in range(self.ngaussian):
            overlap[i, i] = 1.0 + 0.0j
            for j in range(i + 1, self.ngaussian):
                value = cross_correlated_gaussian_data_v270(
                    self.q[i], self.p[i], self.width_matrices[i], self.chirp_matrices[i],
                    self.q[j], self.p[j], self.width_matrices[j], self.chirp_matrices[j],
                )[0]
                overlap[i, j] = value
                overlap[j, i] = np.conj(value)
        return overlap

    @property
    def generalized_norm(self):
        if self.coefficients.ndim != 2 or self.q.ndim != 2:
            return float("nan")
        overlap = self.nuclear_overlap_matrix()
        value = np.einsum(
            "ia,ij,ja->", self.coefficients.conj(), overlap, self.coefficients, optimize=True
        )
        if abs(float(np.imag(value))) > 3.0e-10:
            return float("nan")
        return float(np.real(value))

    def normalized(self):
        self.validate(require_normalized=False)
        return CorrelatedGaussianSpinorStateV270(
            self.q, self.p, self.width_matrices, self.chirp_matrices,
            self.coefficients / np.sqrt(self.generalized_norm), self.time_au,
        ).validate(require_normalized=True)

    def permuted(self, order):
        self.validate(require_normalized=False)
        order = np.asarray(order, dtype=int)
        if order.shape != (self.ngaussian,) or sorted(order.tolist()) != list(range(self.ngaussian)):
            raise ValueError("packet permutation is invalid.")
        return CorrelatedGaussianSpinorStateV270(
            self.q[order], self.p[order], self.width_matrices[order], self.chirp_matrices[order],
            self.coefficients[order], self.time_au,
        ).validate(require_normalized=False)

    def gauge_transformed(self, unitary):
        self.validate(require_normalized=False)
        unitary = np.asarray(unitary, dtype=complex)
        if unitary.shape != (self.nstate, self.nstate) or _scaled_norm_v270(
            unitary.conj().T @ unitary, np.eye(self.nstate)
        ) > 2.0e-11:
            raise ValueError("electronic gauge transformation must be unitary.")
        return CorrelatedGaussianSpinorStateV270(
            self.q, self.p, self.width_matrices, self.chirp_matrices,
            self.coefficients @ unitary.conj(), self.time_au,
        ).validate(require_normalized=False)

    def coordinate_rotated(self, orthogonal):
        self.validate(require_normalized=False)
        orthogonal = np.asarray(orthogonal, dtype=float)
        if orthogonal.shape != (self.ndim, self.ndim) or _scaled_norm_v270(
            orthogonal @ orthogonal.T, np.eye(self.ndim)
        ) > 2.0e-11:
            raise ValueError("coordinate transformation must be orthogonal.")
        return CorrelatedGaussianSpinorStateV270(
            self.q @ orthogonal.T,
            self.p @ orthogonal.T,
            np.asarray([rotate_symmetric_v270(matrix, orthogonal) for matrix in self.width_matrices]),
            np.asarray([rotate_symmetric_v270(matrix, orthogonal) for matrix in self.chirp_matrices]),
            self.coefficients,
            self.time_au,
        ).validate(require_normalized=False)

    @classmethod
    def from_diagonal_v260(cls, state):
        state = state.validate(require_normalized=False)
        return cls(
            state.q,
            state.p,
            np.asarray([np.diag(row) for row in state.widths]),
            np.asarray([np.diag(row) for row in state.chirps]),
            state.coefficients,
            state.time_au,
        ).validate(require_normalized=False)

    def to_diagonal_v260(self, *, tolerance=2.0e-11):
        self.validate(require_normalized=False)
        diagonal_widths = np.asarray([np.diag(matrix) for matrix in self.width_matrices])
        diagonal_chirps = np.asarray([np.diag(matrix) for matrix in self.chirp_matrices])
        width_offdiag = self.width_matrices - np.asarray([np.diag(row) for row in diagonal_widths])
        chirp_offdiag = self.chirp_matrices - np.asarray([np.diag(row) for row in diagonal_chirps])
        if max(float(np.max(np.abs(width_offdiag))), float(np.max(np.abs(chirp_offdiag)))) > tolerance:
            raise ValueError("correlated state cannot be represented by the diagonal v0.26.0 manifold.")
        return DiagonalGaussianSpinorStateV260(
            self.q, self.p, diagonal_widths, diagonal_chirps, self.coefficients, self.time_au
        ).validate(require_normalized=False)

    def as_dict(self):
        self.validate(require_normalized=False)
        return {
            "q": self.q.tolist(),
            "p": self.p.tolist(),
            "width_matrices": self.width_matrices.tolist(),
            "log_width_matrices": self.log_width_matrices.tolist(),
            "chirp_matrices": self.chirp_matrices.tolist(),
            "coefficients": _complex_pairs_v270(self.coefficients),
            "time_au": float(self.time_au),
            "ngaussian": self.ngaussian,
            "ndim": self.ndim,
            "nstate": self.nstate,
            "parameter_count": self.parameter_count,
            "generalized_norm": self.generalized_norm,
        }


def pack_correlated_parameters_v270(state):
    state = state.validate(require_normalized=False)
    return np.concatenate(
        (
            state.coefficients.real.reshape(-1),
            state.coefficients.imag.reshape(-1),
            state.q.reshape(-1),
            state.p.reshape(-1),
            np.concatenate([svec_v270(matrix) for matrix in state.log_width_matrices]),
            np.concatenate([svec_v270(matrix) for matrix in state.chirp_matrices]),
        )
    )


def state_from_correlated_parameters_v270(parameters, *, ngaussian, ndim, nstate, time_au):
    parameters = np.asarray(parameters, dtype=float)
    counts = (ngaussian, ndim, nstate)
    if any(
        isinstance(value, (bool, np.bool_))
        or not isinstance(value, (int, np.integer))
        or int(value) < 1
        for value in counts
    ):
        raise ValueError("ngaussian, ndim, and nstate must be positive integers.")
    ngaussian, ndim, nstate = map(int, counts)
    coefficient_count = ngaussian * nstate
    vector_count = ngaussian * ndim
    matrix_count = ngaussian * symmetric_size_v270(ndim)
    expected = 2 * coefficient_count + 2 * vector_count + 2 * matrix_count
    if parameters.shape != (expected,) or not np.all(np.isfinite(parameters)):
        raise ValueError("correlated parameter vector has an invalid shape or values.")
    coefficients = (
        parameters[:coefficient_count]
        + 1.0j * parameters[coefficient_count : 2 * coefficient_count]
    ).reshape(ngaussian, nstate)
    cursor = 2 * coefficient_count
    q = parameters[cursor : cursor + vector_count].reshape(ngaussian, ndim)
    cursor += vector_count
    p = parameters[cursor : cursor + vector_count].reshape(ngaussian, ndim)
    cursor += vector_count
    log_width_vectors = parameters[cursor : cursor + matrix_count].reshape(
        ngaussian, symmetric_size_v270(ndim)
    )
    cursor += matrix_count
    chirp_vectors = parameters[cursor : cursor + matrix_count].reshape(
        ngaussian, symmetric_size_v270(ndim)
    )
    log_widths = np.asarray([smat_v270(row, ndim) for row in log_width_vectors])
    width_matrices = np.asarray([exp_symmetric_v270(matrix) for matrix in log_widths])
    chirp_matrices = np.asarray([smat_v270(row, ndim) for row in chirp_vectors])
    return CorrelatedGaussianSpinorStateV270(
        q, p, width_matrices, chirp_matrices, coefficients, float(time_au)
    ).validate(require_normalized=False)


def _validate_correlated_domain_v270(state, settings):
    state = state.validate(require_normalized=False)
    settings = settings.validate()
    eigenvalues = state.width_eigenvalues
    if float(np.min(eigenvalues)) < float(settings.minimum_width_eigenvalue):
        raise ValueError("a Gaussian width eigenvalue fell below the configured minimum.")
    if float(np.max(eigenvalues)) > float(settings.maximum_width_eigenvalue):
        raise ValueError("a Gaussian width eigenvalue exceeded the configured maximum.")
    chirp_radius = max(
        float(np.max(np.abs(np.linalg.eigvalsh(matrix))))
        for matrix in state.chirp_matrices
    )
    if chirp_radius > float(settings.maximum_chirp_spectral_radius):
        raise ValueError("a Gaussian chirp spectral radius exceeded its configured maximum.")
    return state


def _kinetic_polynomial_correlated_v270(q, p, width, chirp, inverse_mass):
    q = np.asarray(q, dtype=float)
    p = np.asarray(p, dtype=float)
    width = np.asarray(width, dtype=float)
    chirp = np.asarray(chirp, dtype=float)
    inverse_mass = np.asarray(inverse_mass, dtype=float)
    ndim = len(q)
    if p.shape != (ndim,) or any(
        matrix.shape != (ndim, ndim) for matrix in (width, chirp, inverse_mass)
    ):
        raise ValueError("correlated kinetic polynomial dimensions differ.")
    precision = width - 1.0j * chirp
    factors = [
        _linear_polynomial_v270(
            ndim,
            (precision @ q)[axis] + 1.0j * p[axis],
            -precision[axis],
        )
        for axis in range(ndim)
    ]
    polynomial = {}
    zero = _zero_index_v270(ndim)
    for a in range(ndim):
        for b in range(ndim):
            second_derivative = _poly_add_v270(
                _poly_multiply_v270(factors[a], factors[b]),
                {zero: -precision[a, b]},
            )
            polynomial = _poly_add_v270(
                polynomial,
                _poly_scale_v270(second_derivative, -0.5 * inverse_mass[a, b]),
            )
    return polynomial


def _operator_polynomials_correlated_v270(state, model, packet):
    """Polynomial matrix for ``H g_packet`` in the fixed diabatic frame."""

    ndim = state.ndim
    nstate = state.nstate
    zero = _zero_index_v270(ndim)
    result = [[{} for _ in range(nstate)] for _ in range(nstate)]
    for output in range(nstate):
        for input_state in range(nstate):
            polynomial = {zero: model.H0[output, input_state]}
            for axis in range(ndim):
                polynomial = _poly_add_v270(
                    polynomial,
                    {_monomial_v270(ndim, (axis,)): model.H1[axis, output, input_state]},
                )
            for axis_a in range(ndim):
                for axis_b in range(ndim):
                    polynomial = _poly_add_v270(
                        polynomial,
                        {
                            _monomial_v270(ndim, (axis_a, axis_b)):
                            model.H2[axis_a, axis_b, output, input_state]
                        },
                    )
            result[output][input_state] = polynomial
    kinetic = _kinetic_polynomial_correlated_v270(
        state.q[packet], state.p[packet], state.width_matrices[packet],
        state.chirp_matrices[packet], model.inverse_mass_matrix_au,
    )
    for electronic in range(nstate):
        result[electronic][electronic] = _poly_add_v270(
            result[electronic][electronic], kinetic
        )
    return result


def build_correlated_gaussian_matrices_v270(state, model):
    state = state.validate(require_normalized=False)
    model = model.validate()
    if state.ndim != model.ndim or state.nstate != model.nstate:
        raise ValueError("state dimensions differ from the Hamiltonian model.")
    dimension = state.ngaussian * state.nstate
    overlap = np.zeros((dimension, dimension), dtype=complex)
    hamiltonian = np.zeros((dimension, dimension), dtype=complex)
    identity = np.eye(state.nstate, dtype=complex)
    for i in range(state.ngaussian):
        si = slice(i * state.nstate, (i + 1) * state.nstate)
        for j in range(state.ngaussian):
            sj = slice(j * state.nstate, (j + 1) * state.nstate)
            data = cross_correlated_gaussian_data_v270(
                state.q[i], state.p[i], state.width_matrices[i], state.chirp_matrices[i],
                state.q[j], state.p[j], state.width_matrices[j], state.chirp_matrices[j],
            )
            table = correlated_moment_table_v270(*data, maximum_degree=2)
            overlap[si, sj] = data[0] * identity
            operator = _operator_polynomials_correlated_v270(state, model, j)
            for output in range(state.nstate):
                for input_state in range(state.nstate):
                    hamiltonian[si.start + output, sj.start + input_state] = (
                        integrate_correlated_polynomial_v270(
                            operator[output][input_state], table
                        )
                    )
    if _scaled_norm_v270(overlap, overlap.conj().T) > 4.0e-10:
        raise ValueError("correlated overlap matrix is not Hermitian.")
    if _scaled_norm_v270(hamiltonian, hamiltonian.conj().T) > 4.0e-10:
        raise ValueError("correlated Hamiltonian matrix is not Hermitian.")
    return overlap, hamiltonian


def correlated_variational_energy_v270(state, model):
    state = state.validate(require_normalized=False)
    overlap, hamiltonian = build_correlated_gaussian_matrices_v270(state, model)
    coefficients = state.coefficients.reshape(-1)
    norm = float(np.real(np.vdot(coefficients, overlap @ coefficients)))
    if norm <= 0.0:
        raise ValueError("cannot evaluate the energy of a zero-norm state.")
    value = np.vdot(coefficients, hamiltonian @ coefficients) / norm
    if abs(float(np.imag(value))) > 4.0e-10:
        raise ValueError("correlated variational energy has a non-negligible imaginary part.")
    return float(np.real(value))


def correlated_reduced_density_v270(state, *, normalize=True):
    state = state.validate(require_normalized=False)
    overlap = state.nuclear_overlap_matrix()
    density = state.coefficients.T @ overlap.T @ state.coefficients.conj()
    density = 0.5 * (density + density.conj().T)
    trace = float(np.real(np.trace(density)))
    if normalize:
        if trace <= 0.0:
            raise ValueError("cannot normalize a nonpositive reduced density.")
        density = density / trace
    return density


def _tangent_terms_correlated_v270(state):
    """Return ``(packet,electronic vector,coordinate polynomial)`` in pack order."""

    state = state.validate(require_normalized=False)
    terms = []
    zero = _zero_index_v270(state.ndim)
    for packet in range(state.ngaussian):
        for electronic in range(state.nstate):
            vector = np.zeros(state.nstate, dtype=complex)
            vector[electronic] = 1.0
            terms.append((packet, vector, {zero: 1.0 + 0.0j}))
    for packet in range(state.ngaussian):
        for electronic in range(state.nstate):
            vector = np.zeros(state.nstate, dtype=complex)
            vector[electronic] = 1.0j
            terms.append((packet, vector, {zero: 1.0 + 0.0j}))
    for packet in range(state.ngaussian):
        precision = state.width_matrices[packet] - 1.0j * state.chirp_matrices[packet]
        for axis in range(state.ndim):
            terms.append(
                (
                    packet,
                    state.coefficients[packet],
                    _linear_polynomial_v270(
                        state.ndim,
                        -(precision @ state.q[packet])[axis] - 1.0j * state.p[packet, axis],
                        precision[axis],
                    ),
                )
            )
    for packet in range(state.ngaussian):
        for axis in range(state.ndim):
            slopes = np.zeros(state.ndim, dtype=complex)
            slopes[axis] = 1.0j
            terms.append(
                (
                    packet,
                    state.coefficients[packet],
                    _linear_polynomial_v270(
                        state.ndim, -1.0j * state.q[packet, axis], slopes
                    ),
                )
            )
    basis = symmetric_basis_v270(state.ndim)
    for packet in range(state.ngaussian):
        width = state.width_matrices[packet]
        inverse_width = np.linalg.inv(width)
        log_width = state.log_width_matrices[packet]
        for direction in basis:
            dwidth = exp_frechet_symmetric_v270(log_width, direction)
            normalization = 0.25 * np.trace(inverse_width @ dwidth)
            terms.append(
                (
                    packet,
                    state.coefficients[packet],
                    _poly_add_v270(
                        {zero: normalization},
                        _poly_scale_v270(
                            _shifted_quadratic_v270(dwidth, state.q[packet]), -0.5
                        ),
                    ),
                )
            )
    for packet in range(state.ngaussian):
        for direction in basis:
            terms.append(
                (
                    packet,
                    state.coefficients[packet],
                    _poly_scale_v270(
                        _shifted_quadratic_v270(direction, state.q[packet]), 0.5j
                    ),
                )
            )
    if len(terms) != state.parameter_count:
        raise AssertionError("correlated tangent count disagrees with parameter layout.")
    return terms


def active_correlated_parameter_indices_v270(state, active_shape_mask):
    state = state.validate(require_normalized=False)
    mask = np.asarray(active_shape_mask, dtype=bool)
    if mask.shape != (state.ngaussian,):
        raise ValueError("active shape mask must contain one value per packet.")
    coefficient_count = 2 * state.ngaussian * state.nstate
    indices = list(range(coefficient_count))
    cursor = coefficient_count
    for family_size in (state.ndim, state.ndim, state.symmetric_size, state.symmetric_size):
        for packet in range(state.ngaussian):
            if mask[packet]:
                start = cursor + packet * family_size
                indices.extend(range(start, start + family_size))
        cursor += state.ngaussian * family_size
    return np.asarray(indices, dtype=int)


@dataclass(frozen=True)
class CorrelatedMetricSystemV270:
    metric: np.ndarray
    rhs: np.ndarray
    velocity: np.ndarray
    active_parameter_indices: np.ndarray
    active_shape_mask: np.ndarray
    solve_receipt: MetricSolveReceiptV251
    generalized_norm: float
    energy_hartree: float
    settings: CorrelatedVariationalSettingsV270

    def __post_init__(self):
        for name in ("metric", "rhs", "velocity"):
            object.__setattr__(self, name, np.asarray(getattr(self, name), dtype=float).copy())
        object.__setattr__(
            self, "active_parameter_indices", np.asarray(self.active_parameter_indices, dtype=int).copy()
        )
        object.__setattr__(
            self, "active_shape_mask", np.asarray(self.active_shape_mask, dtype=bool).copy()
        )

    def validate(self):
        settings = self.settings.validate()
        if self.metric.ndim != 2 or self.metric.shape[0] != self.metric.shape[1]:
            raise ValueError("stored correlated metric must be square.")
        active_count = self.metric.shape[0]
        if self.rhs.shape != (active_count,):
            raise ValueError("stored correlated metric RHS has an incompatible shape.")
        if self.velocity.ndim != 1 or len(self.active_parameter_indices) != active_count:
            raise ValueError("stored velocity or active index map has an invalid shape.")
        if np.any(self.active_parameter_indices < 0) or np.any(
            self.active_parameter_indices >= len(self.velocity)
        ):
            raise ValueError("active parameter index lies outside the full vector.")
        if len(np.unique(self.active_parameter_indices)) != active_count:
            raise ValueError("active parameter indices contain duplicates.")
        if not all(np.all(np.isfinite(value)) for value in (self.metric, self.rhs, self.velocity)):
            raise ValueError("stored correlated metric system is non-finite.")
        expected_velocity, expected_receipt = solve_variational_metric_v251(
            self.metric, self.rhs, settings=settings
        )
        if _scaled_norm_v270(
            self.velocity[self.active_parameter_indices], expected_velocity
        ) > settings.structural_tolerance:
            raise ValueError("stored velocity disagrees with its SVD solve.")
        inactive = np.ones(len(self.velocity), dtype=bool)
        inactive[self.active_parameter_indices] = False
        if np.max(np.abs(self.velocity[inactive]), initial=0.0) > settings.structural_tolerance:
            raise ValueError("inactive correlated shape coordinates must have zero velocity.")
        if _scaled_norm_v270(
            self.solve_receipt.singular_values, expected_receipt.singular_values
        ) > settings.structural_tolerance:
            raise ValueError("stored correlated metric spectrum is inconsistent.")
        if not np.isfinite(float(self.generalized_norm)) or self.generalized_norm <= 0.0:
            raise ValueError("stored generalized norm must be positive.")
        if not np.isfinite(float(self.energy_hartree)):
            raise ValueError("stored correlated energy must be finite.")
        return self

    def as_dict(self):
        self.validate()
        return {
            "metric": self.metric.tolist(),
            "rhs": self.rhs.tolist(),
            "velocity": self.velocity.tolist(),
            "active_parameter_indices": self.active_parameter_indices.tolist(),
            "active_shape_mask": self.active_shape_mask.tolist(),
            "solve_receipt": self.solve_receipt.as_dict(),
            "generalized_norm": float(self.generalized_norm),
            "energy_hartree": float(self.energy_hartree),
            "settings": self.settings.as_dict(),
        }


def build_correlated_metric_system_v270(
    state,
    model,
    *,
    settings=CorrelatedVariationalSettingsV270(),
    active_shape_mask=None,
):
    settings = settings.validate()
    state = _validate_correlated_domain_v270(state, settings)
    model = model.validate()
    if state.ndim != model.ndim or state.nstate != model.nstate:
        raise ValueError("state dimensions differ from the Hamiltonian model.")
    if active_shape_mask is None:
        active_shape_mask = np.ones(state.ngaussian, dtype=bool)
    active_shape_mask = np.asarray(active_shape_mask, dtype=bool)
    active_indices = active_correlated_parameter_indices_v270(state, active_shape_mask)
    terms = _tangent_terms_correlated_v270(state)
    count = len(terms)
    full_metric = np.zeros((count, count), dtype=float)
    full_rhs = np.zeros(count, dtype=float)
    moment_cache = {}
    operator_cache = {}
    for i in range(state.ngaussian):
        operator_cache[i] = _operator_polynomials_correlated_v270(state, model, i)
        for j in range(state.ngaussian):
            data = cross_correlated_gaussian_data_v270(
                state.q[i], state.p[i], state.width_matrices[i], state.chirp_matrices[i],
                state.q[j], state.p[j], state.width_matrices[j], state.chirp_matrices[j],
            )
            moment_cache[(i, j)] = correlated_moment_table_v270(
                *data, maximum_degree=4
            )
    for mu, (packet_i, vector_i, polynomial_i) in enumerate(terms):
        conjugate_i = _poly_conjugate_v270(polynomial_i)
        for nu, (packet_j, vector_j, polynomial_j) in enumerate(terms):
            nuclear = integrate_correlated_polynomial_v270(
                _poly_multiply_v270(conjugate_i, polynomial_j),
                moment_cache[(packet_i, packet_j)],
            )
            full_metric[mu, nu] = float(np.real(np.vdot(vector_i, vector_j) * nuclear))
        projection = 0.0 + 0.0j
        for packet_j in range(state.ngaussian):
            operator = operator_cache[packet_j]
            for output in range(state.nstate):
                electronic_projection = np.conj(vector_i[output])
                if electronic_projection == 0.0:
                    continue
                for input_state in range(state.nstate):
                    amplitude = state.coefficients[packet_j, input_state]
                    if amplitude == 0.0:
                        continue
                    projection += (
                        electronic_projection
                        * amplitude
                        * integrate_correlated_polynomial_v270(
                            _poly_multiply_v270(
                                conjugate_i, operator[output][input_state]
                            ),
                            moment_cache[(packet_i, packet_j)],
                        )
                    )
        full_rhs[mu] = float(np.imag(projection))
    full_metric = 0.5 * (full_metric + full_metric.T)
    metric = full_metric[np.ix_(active_indices, active_indices)]
    rhs = full_rhs[active_indices]
    active_velocity, receipt = solve_variational_metric_v251(metric, rhs, settings=settings)
    velocity = np.zeros(count, dtype=float)
    velocity[active_indices] = active_velocity
    return CorrelatedMetricSystemV270(
        metric=metric,
        rhs=rhs,
        velocity=velocity,
        active_parameter_indices=active_indices,
        active_shape_mask=active_shape_mask,
        solve_receipt=receipt,
        generalized_norm=state.generalized_norm,
        energy_hartree=correlated_variational_energy_v270(state, model),
        settings=settings,
    ).validate()


@dataclass(frozen=True)
class CorrelatedImplicitMidpointStepV270:
    start: CorrelatedGaussianSpinorStateV270
    end: CorrelatedGaussianSpinorStateV270
    model: QuadraticSpinHamiltonianNDV260
    settings: CorrelatedVariationalSettingsV270
    dt_au: float
    active_shape_mask: np.ndarray
    midpoint_parameters: np.ndarray
    midpoint_system: CorrelatedMetricSystemV270
    nonlinear_success: bool
    nonlinear_status: int
    nonlinear_message: str
    nonlinear_function_evaluations: int
    nonlinear_residual: np.ndarray
    nonlinear_residual_norm: float
    predictor_residual_norm: float
    start_norm: float
    end_norm: float
    start_energy_hartree: float
    end_energy_hartree: float

    def __post_init__(self):
        object.__setattr__(
            self, "active_shape_mask", np.asarray(self.active_shape_mask, dtype=bool).copy()
        )
        object.__setattr__(
            self, "midpoint_parameters", np.asarray(self.midpoint_parameters, dtype=float).copy()
        )
        object.__setattr__(
            self, "nonlinear_residual", np.asarray(self.nonlinear_residual, dtype=float).copy()
        )

    @property
    def norm_change(self):
        return float(self.end_norm - self.start_norm)

    @property
    def energy_change_hartree(self):
        return float(self.end_energy_hartree - self.start_energy_hartree)

    @property
    def maximum_log_width_frobenius_change(self):
        return float(
            max(
                np.linalg.norm(end - start)
                for start, end in zip(
                    self.start.log_width_matrices, self.end.log_width_matrices
                )
            )
        )

    def validate(self):
        settings = self.settings.validate()
        self.model.validate()
        tolerance = max(settings.maximum_step_norm_drift, settings.structural_tolerance)
        self.start.validate(require_normalized=True, tolerance=tolerance)
        self.end.validate(require_normalized=True, tolerance=tolerance)
        if self.start.q.shape != self.end.q.shape or self.start.coefficients.shape != self.end.coefficients.shape:
            raise ValueError("correlated TDVP step changed state dimensions.")
        if self.active_shape_mask.shape != (self.start.ngaussian,):
            raise ValueError("correlated TDVP active mask has an invalid shape.")
        if not np.isfinite(float(self.dt_au)) or self.dt_au == 0.0:
            raise ValueError("correlated TDVP dt must be finite and nonzero.")
        if abs(self.end.time_au - (self.start.time_au + self.dt_au)) > settings.structural_tolerance:
            raise ValueError("correlated TDVP endpoint time is inconsistent.")
        if type(self.nonlinear_success) is not bool or not self.nonlinear_success:
            raise ValueError("correlated TDVP nonlinear solve was not successful.")
        theta_start = pack_correlated_parameters_v270(self.start)
        theta_end = pack_correlated_parameters_v270(self.end)
        expected_midpoint = 0.5 * (theta_start + theta_end)
        if _scaled_norm_v270(self.midpoint_parameters, expected_midpoint) > settings.structural_tolerance:
            raise ValueError("stored correlated midpoint parameters are inconsistent.")
        expected_residual = theta_end - theta_start - self.dt_au * self.midpoint_system.velocity
        if _scaled_norm_v270(self.nonlinear_residual, expected_residual) > settings.structural_tolerance:
            raise ValueError("stored correlated nonlinear residual is inconsistent.")
        expected_residual_norm = float(np.linalg.norm(expected_residual))
        if abs(self.nonlinear_residual_norm - expected_residual_norm) > settings.structural_tolerance:
            raise ValueError("stored correlated residual norm is inconsistent.")
        if self.nonlinear_residual_norm > settings.nonlinear_residual_tolerance:
            raise ValueError("correlated TDVP nonlinear residual exceeds its gate.")
        if abs(self.norm_change) > settings.maximum_step_norm_drift:
            raise ValueError("correlated TDVP norm drift exceeds its gate.")
        if (
            self.maximum_log_width_frobenius_change
            > settings.maximum_step_log_width_frobenius_change
        ):
            raise ValueError("correlated TDVP log-width step exceeds its gate.")
        inactive = ~self.active_shape_mask
        if np.any(inactive):
            for start, end in (
                (self.start.q[inactive], self.end.q[inactive]),
                (self.start.p[inactive], self.end.p[inactive]),
                (self.start.width_matrices[inactive], self.end.width_matrices[inactive]),
                (self.start.chirp_matrices[inactive], self.end.chirp_matrices[inactive]),
            ):
                if not np.array_equal(start, end):
                    raise ValueError("inactive correlated newborn shapes changed during activation.")
        self.midpoint_system.validate()
        return self

    def as_dict(self):
        self.validate()
        return {
            "start": self.start.as_dict(),
            "end": self.end.as_dict(),
            "dt_au": float(self.dt_au),
            "active_shape_mask": self.active_shape_mask.tolist(),
            "midpoint_parameters": self.midpoint_parameters.tolist(),
            "midpoint_system": self.midpoint_system.as_dict(),
            "nonlinear": {
                "success": self.nonlinear_success,
                "status": int(self.nonlinear_status),
                "message": str(self.nonlinear_message),
                "function_evaluations": int(self.nonlinear_function_evaluations),
                "residual": self.nonlinear_residual.tolist(),
                "residual_norm": float(self.nonlinear_residual_norm),
                "predictor_residual_norm": float(self.predictor_residual_norm),
            },
            "start_norm": float(self.start_norm),
            "end_norm": float(self.end_norm),
            "norm_change": self.norm_change,
            "start_energy_hartree": float(self.start_energy_hartree),
            "end_energy_hartree": float(self.end_energy_hartree),
            "energy_change_hartree": self.energy_change_hartree,
            "maximum_log_width_frobenius_change": self.maximum_log_width_frobenius_change,
        }


def correlated_implicit_midpoint_step_v270(
    state,
    model,
    dt_au,
    *,
    settings=CorrelatedVariationalSettingsV270(),
    active_shape_mask=None,
):
    settings = settings.validate()
    model = model.validate()
    state = _validate_correlated_domain_v270(state, settings).validate(
        require_normalized=True,
        tolerance=max(settings.structural_tolerance, settings.maximum_step_norm_drift),
    )
    if state.ndim != model.ndim or state.nstate != model.nstate:
        raise ValueError("state dimensions differ from the Hamiltonian model.")
    dt = float(dt_au)
    if not np.isfinite(dt) or dt == 0.0:
        raise ValueError("implicit midpoint dt must be finite and nonzero.")
    if active_shape_mask is None:
        active_shape_mask = np.ones(state.ngaussian, dtype=bool)
    active_shape_mask = np.asarray(active_shape_mask, dtype=bool)
    if active_shape_mask.shape != (state.ngaussian,):
        raise ValueError("active shape mask must contain one value per packet.")
    theta_start = pack_correlated_parameters_v270(state)
    active_indices = active_correlated_parameter_indices_v270(state, active_shape_mask)
    frozen = np.ones(theta_start.size, dtype=bool)
    frozen[active_indices] = False
    initial_system = build_correlated_metric_system_v270(
        state, model, settings=settings, active_shape_mask=active_shape_mask
    )
    predictor = theta_start + dt * initial_system.velocity
    predictor[frozen] = theta_start[frozen]

    def residual(theta_end):
        theta_end = np.asarray(theta_end, dtype=float).copy()
        theta_end[frozen] = theta_start[frozen]
        midpoint = 0.5 * (theta_start + theta_end)
        midpoint_state = state_from_correlated_parameters_v270(
            midpoint,
            ngaussian=state.ngaussian,
            ndim=state.ndim,
            nstate=state.nstate,
            time_au=state.time_au + 0.5 * dt,
        )
        midpoint_system = build_correlated_metric_system_v270(
            midpoint_state, model, settings=settings, active_shape_mask=active_shape_mask
        )
        value = theta_end - theta_start - dt * midpoint_system.velocity
        value[frozen] = theta_end[frozen] - theta_start[frozen]
        return value

    predictor_residual_norm = float(np.linalg.norm(residual(predictor)))
    solution = root(
        residual,
        predictor,
        method="hybr",
        options={
            "xtol": float(settings.nonlinear_xtol),
            "maxfev": int(settings.nonlinear_max_function_evaluations),
            "factor": 0.05,
            # Coefficients, Cartesian vectors, and orthonormal svec blocks all
            # receive identical solver scaling; this is rotation covariant.
            "diag": np.ones_like(theta_start),
        },
    )
    theta_end = np.asarray(solution.x, dtype=float)
    theta_end[frozen] = theta_start[frozen]
    nonlinear_residual = np.asarray(residual(theta_end), dtype=float)
    nonlinear_residual_norm = float(np.linalg.norm(nonlinear_residual))
    if not bool(solution.success) or nonlinear_residual_norm > settings.nonlinear_residual_tolerance:
        raise RuntimeError(
            "correlated implicit midpoint TDVP solve failed: "
            f"success={bool(solution.success)}, status={int(solution.status)}, "
            f"residual={nonlinear_residual_norm:.6e}, message={solution.message}"
        )
    end = state_from_correlated_parameters_v270(
        theta_end,
        ngaussian=state.ngaussian,
        ndim=state.ndim,
        nstate=state.nstate,
        time_au=state.time_au + dt,
    ).validate(
        require_normalized=True,
        tolerance=max(settings.structural_tolerance, settings.maximum_step_norm_drift),
    )
    # Frozen log-width coordinates reconstruct as exp(log(Gamma)), which is
    # mathematically identical but need not be bitwise identical.  Restore the
    # dormant packet data from the source state so the lifecycle's exact-freeze
    # contract is literal, not merely tolerance based.
    inactive_shape = ~active_shape_mask
    if np.any(inactive_shape):
        q_end = end.q.copy()
        p_end = end.p.copy()
        width_end = end.width_matrices.copy()
        chirp_end = end.chirp_matrices.copy()
        q_end[inactive_shape] = state.q[inactive_shape]
        p_end[inactive_shape] = state.p[inactive_shape]
        width_end[inactive_shape] = state.width_matrices[inactive_shape]
        chirp_end[inactive_shape] = state.chirp_matrices[inactive_shape]
        end = CorrelatedGaussianSpinorStateV270(
            q_end, p_end, width_end, chirp_end, end.coefficients, end.time_au
        ).validate(
            require_normalized=True,
            tolerance=max(settings.structural_tolerance, settings.maximum_step_norm_drift),
        )
    _validate_correlated_domain_v270(end, settings)
    midpoint_parameters = 0.5 * (theta_start + theta_end)
    midpoint_state = state_from_correlated_parameters_v270(
        midpoint_parameters,
        ngaussian=state.ngaussian,
        ndim=state.ndim,
        nstate=state.nstate,
        time_au=state.time_au + 0.5 * dt,
    )
    midpoint_system = build_correlated_metric_system_v270(
        midpoint_state, model, settings=settings, active_shape_mask=active_shape_mask
    )
    return CorrelatedImplicitMidpointStepV270(
        start=state,
        end=end,
        model=model,
        settings=settings,
        dt_au=dt,
        active_shape_mask=active_shape_mask,
        midpoint_parameters=midpoint_parameters,
        midpoint_system=midpoint_system,
        nonlinear_success=bool(solution.success),
        nonlinear_status=int(solution.status),
        nonlinear_message=str(solution.message),
        nonlinear_function_evaluations=int(solution.nfev),
        nonlinear_residual=nonlinear_residual,
        nonlinear_residual_norm=nonlinear_residual_norm,
        predictor_residual_norm=predictor_residual_norm,
        start_norm=state.generalized_norm,
        end_norm=end.generalized_norm,
        start_energy_hartree=correlated_variational_energy_v270(state, model),
        end_energy_hartree=correlated_variational_energy_v270(end, model),
    ).validate()


@dataclass(frozen=True)
class CorrelatedTDVPTrajectoryV270:
    initial_state: CorrelatedGaussianSpinorStateV270
    final_state: CorrelatedGaussianSpinorStateV270
    model: QuadraticSpinHamiltonianNDV260
    settings: CorrelatedVariationalSettingsV270
    steps: tuple

    @property
    def maximum_norm_drift(self):
        values = [abs(step.norm_change) for step in self.steps]
        values.append(abs(self.final_state.generalized_norm - self.initial_state.generalized_norm))
        return float(max(values, default=0.0))

    @property
    def maximum_energy_drift_hartree(self):
        initial = correlated_variational_energy_v270(self.initial_state, self.model)
        values = [
            abs(correlated_variational_energy_v270(step.end, self.model) - initial)
            for step in self.steps
        ]
        return float(max(values, default=0.0))

    def validate(self):
        settings = self.settings.validate()
        self.model.validate()
        self.initial_state.validate(require_normalized=True, tolerance=settings.maximum_step_norm_drift)
        self.final_state.validate(require_normalized=True, tolerance=settings.maximum_step_norm_drift)
        previous = self.initial_state
        for step in self.steps:
            step.validate()
            if _scaled_norm_v270(
                pack_correlated_parameters_v270(previous),
                pack_correlated_parameters_v270(step.start),
            ) > settings.structural_tolerance:
                raise ValueError("correlated TDVP trajectory steps are not contiguous.")
            previous = step.end
        if _scaled_norm_v270(
            pack_correlated_parameters_v270(previous),
            pack_correlated_parameters_v270(self.final_state),
        ) > settings.structural_tolerance:
            raise ValueError("correlated TDVP final state differs from the final step.")
        return self

    def as_dict(self):
        self.validate()
        return {
            "schema": CORRELATED_TDVP_SCHEMA_V270,
            "ansatz": CORRELATED_TDVP_ANSATZ_V270,
            "model_fingerprint": self.model.fingerprint(),
            "settings": self.settings.as_dict(),
            "initial_state": self.initial_state.as_dict(),
            "final_state": self.final_state.as_dict(),
            "steps": [step.as_dict() for step in self.steps],
            "maximum_norm_drift": self.maximum_norm_drift,
            "maximum_energy_drift_hartree": self.maximum_energy_drift_hartree,
        }

    def fingerprint(self):
        return _sha256_v270(self.as_dict())


def run_correlated_tdvp_v270(
    initial_state,
    model,
    dt_au,
    steps,
    *,
    settings=CorrelatedVariationalSettingsV270(),
    active_shape_mask=None,
):
    settings = settings.validate()
    initial_state = initial_state.validate(
        require_normalized=True, tolerance=settings.maximum_step_norm_drift
    )
    if isinstance(steps, (bool, np.bool_)) or not isinstance(steps, (int, np.integer)) or int(steps) < 0:
        raise ValueError("steps must be a nonnegative integer.")
    current = initial_state
    receipts = []
    for _ in range(int(steps)):
        receipt = correlated_implicit_midpoint_step_v270(
            current,
            model,
            dt_au,
            settings=settings,
            active_shape_mask=active_shape_mask,
        )
        receipts.append(receipt)
        current = receipt.end
    return CorrelatedTDVPTrajectoryV270(
        initial_state=initial_state,
        final_state=current,
        model=model,
        settings=settings,
        steps=tuple(receipts),
    ).validate()


def evaluate_correlated_state_v270(state, points):
    """Evaluate ``Psi`` at ``points[...,ndim]``."""

    state = state.validate(require_normalized=False)
    points = np.asarray(points, dtype=float)
    if points.shape == () or points.shape[-1] != state.ndim or not np.all(np.isfinite(points)):
        raise ValueError("evaluation points must be finite with final axis ndim.")
    wavefunction = np.zeros(points.shape[:-1] + (state.nstate,), dtype=complex)
    for packet in range(state.ngaussian):
        displacement = points - state.q[packet]
        width = state.width_matrices[packet]
        chirp = state.chirp_matrices[packet]
        logdet = float(np.sum(np.log(np.linalg.eigvalsh(width))))
        normalization = float(np.exp(0.25 * (logdet - state.ndim * np.log(np.pi))))
        exponent = (
            -0.5 * np.einsum("...a,ab,...b->...", displacement, width, displacement)
            + 0.5j * np.einsum("...a,ab,...b->...", displacement, chirp, displacement)
            + 1.0j * np.einsum("...a,a->...", displacement, state.p[packet])
        )
        gaussian = normalization * np.exp(exponent)
        wavefunction += gaussian[..., None] * state.coefficients[packet]
    return wavefunction


def correlated_state_on_grid_v270(state, grid):
    points = grid.validate().mesh()
    values = evaluate_correlated_state_v270(state, points)
    return np.moveaxis(values, -1, 0)


def residual_coupling_correlated_v270(
    state,
    model,
    velocity,
    *,
    q,
    p,
    width_matrix,
    chirp_matrix,
):
    """Return ``<g_candidate,a|dPsi/dt+i H Psi>`` for every electronic state."""

    state = state.validate(require_normalized=False)
    model = model.validate()
    velocity = np.asarray(velocity, dtype=float)
    if velocity.shape != (state.parameter_count,) or not np.all(np.isfinite(velocity)):
        raise ValueError("correlated TDVP velocity has an invalid shape or values.")
    candidate = CorrelatedGaussianSpinorStateV270(
        np.asarray(q, dtype=float)[None, :],
        np.asarray(p, dtype=float)[None, :],
        np.asarray(width_matrix, dtype=float)[None, :, :],
        np.asarray(chirp_matrix, dtype=float)[None, :, :],
        np.ones((1, state.nstate), dtype=complex),
        state.time_au,
    ).validate(require_normalized=False)
    if candidate.ndim != state.ndim:
        raise ValueError("candidate geometry differs from the state dimensionality.")
    tables = {}
    for packet in range(state.ngaussian):
        data = cross_correlated_gaussian_data_v270(
            candidate.q[0], candidate.p[0], candidate.width_matrices[0],
            candidate.chirp_matrices[0], state.q[packet], state.p[packet],
            state.width_matrices[packet], state.chirp_matrices[packet],
        )
        tables[packet] = correlated_moment_table_v270(*data, maximum_degree=4)
    derivative = np.zeros(state.nstate, dtype=complex)
    for speed, (packet, electronic_vector, polynomial) in zip(
        velocity, _tangent_terms_correlated_v270(state)
    ):
        if speed != 0.0:
            derivative += float(speed) * electronic_vector * integrate_correlated_polynomial_v270(
                polynomial, tables[packet]
            )
    hamiltonian_action = np.zeros(state.nstate, dtype=complex)
    for packet in range(state.ngaussian):
        operator = _operator_polynomials_correlated_v270(state, model, packet)
        for output in range(state.nstate):
            for input_state in range(state.nstate):
                amplitude = state.coefficients[packet, input_state]
                if amplitude != 0.0:
                    hamiltonian_action[output] += amplitude * integrate_correlated_polynomial_v270(
                        operator[output][input_state], tables[packet]
                    )
    return derivative + 1.0j * hamiltonian_action


def _velocity_blocks_v270(state, velocity):
    state = state.validate(require_normalized=False)
    velocity = np.asarray(velocity, dtype=float)
    if velocity.shape != (state.parameter_count,) or not np.all(np.isfinite(velocity)):
        raise ValueError("correlated velocity has an invalid shape or values.")
    coefficient_count = state.ngaussian * state.nstate
    vector_count = state.ngaussian * state.ndim
    matrix_count = state.ngaussian * state.symmetric_size
    cdot = (
        velocity[:coefficient_count]
        + 1.0j * velocity[coefficient_count : 2 * coefficient_count]
    ).reshape(state.ngaussian, state.nstate)
    cursor = 2 * coefficient_count
    qdot = velocity[cursor : cursor + vector_count].reshape(state.ngaussian, state.ndim)
    cursor += vector_count
    pdot = velocity[cursor : cursor + vector_count].reshape(state.ngaussian, state.ndim)
    cursor += vector_count
    edot = velocity[cursor : cursor + matrix_count].reshape(
        state.ngaussian, state.symmetric_size
    )
    cursor += matrix_count
    bdot = velocity[cursor : cursor + matrix_count].reshape(
        state.ngaussian, state.symmetric_size
    )
    return cdot, qdot, pdot, edot, bdot


def _pack_velocity_blocks_v270(cdot, qdot, pdot, edot, bdot):
    return np.concatenate(
        (
            np.asarray(cdot).real.reshape(-1), np.asarray(cdot).imag.reshape(-1),
            np.asarray(qdot).reshape(-1), np.asarray(pdot).reshape(-1),
            np.asarray(edot).reshape(-1), np.asarray(bdot).reshape(-1),
        )
    )


def rotate_correlated_velocity_v270(state, velocity, orthogonal):
    """Transform a packed tangent velocity under an orthogonal coordinate change."""

    state = state.validate(require_normalized=False)
    orthogonal = np.asarray(orthogonal, dtype=float)
    if orthogonal.shape != (state.ndim, state.ndim) or _scaled_norm_v270(
        orthogonal @ orthogonal.T, np.eye(state.ndim)
    ) > 2.0e-11:
        raise ValueError("coordinate transformation must be orthogonal.")
    cdot, qdot, pdot, edot, bdot = _velocity_blocks_v270(state, velocity)
    edot_rotated = np.asarray(
        [
            svec_v270(rotate_symmetric_v270(smat_v270(row, state.ndim), orthogonal))
            for row in edot
        ]
    )
    bdot_rotated = np.asarray(
        [
            svec_v270(rotate_symmetric_v270(smat_v270(row, state.ndim), orthogonal))
            for row in bdot
        ]
    )
    return _pack_velocity_blocks_v270(
        cdot, qdot @ orthogonal.T, pdot @ orthogonal.T, edot_rotated, bdot_rotated
    )


def gauge_correlated_velocity_v270(state, velocity, unitary):
    state = state.validate(require_normalized=False)
    unitary = np.asarray(unitary, dtype=complex)
    state.gauge_transformed(unitary)
    cdot, qdot, pdot, edot, bdot = _velocity_blocks_v270(state, velocity)
    return _pack_velocity_blocks_v270(cdot @ unitary.conj(), qdot, pdot, edot, bdot)


def permute_correlated_velocity_v270(state, velocity, order):
    state = state.validate(require_normalized=False)
    order = np.asarray(order, dtype=int)
    state.permuted(order)
    cdot, qdot, pdot, edot, bdot = _velocity_blocks_v270(state, velocity)
    return _pack_velocity_blocks_v270(
        cdot[order], qdot[order], pdot[order], edot[order], bdot[order]
    )


V270_CORRELATED_TDVP_CLAIMS = {
    "full_correlated_width_matrices_validated": True,
    "log_euclidean_positive_width_parameterization_validated": True,
    "full_symmetric_chirp_matrices_validated": True,
    "multivariate_complex_gaussian_moments_validated": True,
    "arbitrary_orthogonal_coordinate_covariance_validated": True,
    "full_positive_definite_mass_matrix_validated": True,
    "implicit_midpoint_nonlinear_solve_validated": True,
    "svd_metric_null_space_handling_validated": True,
    "complete_spinor_complex_soc_validated": True,
    "packet_permutation_covariance_validated": True,
    "constant_electronic_gauge_covariance_validated": True,
    "one_dimensional_v0260_reduction_validated": True,
    "coordinate_dependent_electronic_gauge_covariance_validated": False,
    "real_pyscf_soc_trajectory_admitted": False,
    "general_ab_initio_soc_accuracy_validated": False,
}
